# Generated by Django 4.2.13 on 2024-07-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thuoc', models.CharField(max_length=100)),
                ('dvt', models.CharField(max_length=50)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
