# Generated by Django 5.0.6 on 2024-06-27 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='benh_nhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_benh_nhan', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Mã bệnh nhân phải gồm 8 chữ số.', regex='^\\d{8}$')])),
                ('ho_ten', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField()),
                ('khoa', models.CharField(choices=[('Khoa Khám Bệnh', 'Khoa Khám Bệnh'), ('Khoa Ngoại', 'Khoa Ngoại'), ('Khoa Nội Nhiễm', 'Khoa Nội Nhiễm'), ('Khoa Chăm Sóc Giảm Nhẹ', 'Khoa Chăm Sóc Giảm Nhẹ'), ('Khoa Dưỡng Lão Nam', 'Khoa Dưỡng Lão Nam'), ('Khoa Dưỡng Lão Nữ', 'Khoa  Dưỡng Lão Nữ'), ('Khoa Khám Bệnh Nội Viện', 'Khoa Khám Bệnh Nội Viện'), ('Khoa Tâm Thần', 'Khoa Tâm Thần')], max_length=100)),
            ],
        ),
    ]
