# Generated by Django 5.0.6 on 2024-06-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benh_nhan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='benh_nhan',
            new_name='BenhNhan',
        ),
    ]
