# Generated by Django 5.0.6 on 2024-07-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danh_muc_thuoc', '0002_rename_danhmuc_thuoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctPhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu_nhap', models.CharField(max_length=20, unique=True)),
                ('ngay_nhap', models.DateField()),
                ('so_luong_nhap', models.PositiveIntegerField()),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danh_muc_thuoc.thuoc')),
            ],
        ),
    ]
