# Generated by Django 5.0.6 on 2024-07-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phieu_nhap_kho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu_nhap', models.CharField(blank=True, max_length=20, unique=True)),
                ('ngay_nhap', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ctphieunhap',
            name='ngay_nhap',
        ),
        migrations.RemoveField(
            model_name='ctphieunhap',
            name='so_phieu_nhap',
        ),
        migrations.AddField(
            model_name='ctphieunhap',
            name='phieu_nhap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phieu_nhap_kho.phieunhap'),
        ),
    ]
