# Generated by Django 4.2.13 on 2024-07-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phieu_nhap_kho', '0002_phieunhap_remove_ctphieunhap_ngay_nhap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieunhap',
            name='so_phieu_nhap',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
