# Generated by Django 5.0.6 on 2024-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0003_kho_ngay_nhap'),
    ]

    operations = [
        migrations.AddField(
            model_name='kho',
            name='don_gia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='kho',
            name='dvt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
