# Generated by Django 5.0.6 on 2024-07-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0004_kho_don_gia_kho_dvt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kho',
            name='nam',
        ),
        migrations.RemoveField(
            model_name='kho',
            name='thang',
        ),
        migrations.RemoveField(
            model_name='kho',
            name='ton_dau',
        ),
        migrations.AlterField(
            model_name='kho',
            name='dvt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kho',
            name='ngay_nhap',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kho',
            name='so_luong_nhap',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kho',
            name='so_luong_xuat',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kho',
            name='ton_cuoi',
            field=models.PositiveIntegerField(),
        ),
    ]
